apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: opslevel
build:
  artifacts:
  - image: public.ecr.aws/e1n4f2i6/kubectl-opslevel
    docker:
      dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
    - test/k8s/*.yaml
  helm:
    releases:
    - name: localdev
      namespace: opslevel
      createNamespace: true
      repo: https://opslevel.github.io/helm-charts 
      remoteChart: kubernetes-sync
      valuesFiles:
        - ./values.yaml
      setFiles:
        sync.config: ./opslevel-k8s.yaml
      artifactOverrides:
        image: public.ecr.aws/e1n4f2i6/kubectl-opslevel # no tag present!
        # Skaffold continuously tags your image, so no need to put one here.